language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -U -r requirements.txt
  - pip install -U -r requirements_dev.txt

# command to run tests
script:
  - pytest